test-libs=pilot_atk pilot_wtk pilot_utk

bin-$(CONFIG_PILOT_TEST)+=test0
test0_CFLAGS=$(CONFIG_PILOT_CFLAGS)
test0_LDFLAGS=$(CONFIG_PILOT_LDFLAGS)
test0_LIBRARY=$(CONFIG_PILOT_LIBRARY)
bin-$(CONFIG_PILOT_TEST2)+=test1
test1_CFLAGS=$(CONFIG_PILOT_CFLAGS)
test1_LDFLAGS=$(CONFIG_PILOT_LDFLAGS)
test1_LIBRARY=$(CONFIG_PILOT_LIBRARY)
bin-$(CONFIG_PILOT_TEST2)+=test1-2
test1-2_CFLAGS=$(CONFIG_PILOT_CFLAGS)
test1-2_LDFLAGS=$(CONFIG_PILOT_LDFLAGS)
test1-2_LIBRARY=$(CONFIG_PILOT_LIBRARY)
bin-$(CONFIG_PILOT_TEST2)+=test1-3
test1-3_CFLAGS=$(CONFIG_PILOT_CFLAGS)
test1-3_LIBRARY=$(CONFIG_PILOT_LIBRARY)
test1-3_LDFLAGS=$(CONFIG_PILOT_LDFLAGS)
test1-3_LDFLAGS+=-lpthread
bin-$(CONFIG_PILOT_TEST2)+=test3
test3-objs=test3.o test3.res.o
test3_CFLAGS=$(CONFIG_PILOT_CFLAGS)
test3.res_CFLAGS=$(CONFIG_PILOT_CFLAGS)
test3_LIBRARY=$(CONFIG_PILOT_LIBRARY)
test3_LDFLAGS=$(CONFIG_PILOT_LDFLAGS)
test3_LDFLAGS+=-rdynamic

